puts "The students of my chohort at Makers Academy"
puts "-------------"
puts "Gabriel Ar..."
puts "Bibiana Am..."
puts "Jin Da.."
puts "Sanda Go..."
puts "Hannah Car" 
puts "Huy Le..."
puts "Marcin Wa..."